### ISSUE TITLE
[Question] Select fields on a subscribed query

### ISSUE THREAD

**Issue by HZSamir** [rafamel/multitude#1]
Hello,
I would like to select specific fields on the following query:
```
const sub = this.db.files.find().$.subscribe(files => {
      if (!files) {
        return;
      }
      this.saveToState(files);
    });
```
I have tried a few notations, to no avail for now.
Is this possible?
Thank you.

**Comment by rafamel** [comment]
Hi, are you using rxdb or is this a general rxjs observable question? If it is, this is not the rxdb-utils repo, please open the issue there (check the documentation for the select plugin first).

**Comment by HZSamir** [comment]
Indeed, this is an rxdb-utils question. I apologize for the confusion.
